scala-debugger-api/src/it/scala/org/senkbeil/debugger/AttachingDebuggerIntegrationSpec.scala
scala-debugger-api/src/it/scala/test/TestUtilities.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/AttachingDebugger.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/LaunchingDebugger.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/AttachingDebuggerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/LaunchingDebuggerSpec.scala
scala-debugger-test/src/main/scala/org/senkbeil/test/misc/AttachingMain.scala

Add attaching debugger

---

README.md
project/Common.scala

Refactored rcsenkbeil to chipsenkbeil

---

scala-debugger-api/src/main/scala/org/senkbeil/debugger/events/EventManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/events/EventProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/events/EventSetProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/events/LoopingTaskRunner.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/events/EventManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/events/EventProcessorSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/events/EventSetProcessorSpec.scala

Refactored event manager into three pieces

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/LaunchingDebuggerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/ListeningDebuggerIntegrationSpec.scala
scala-debugger-api/src/it/scala/test/TestUtilities.scala
scala-debugger-api/src/it/scala/test/VirtualMachineFixtures.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/ListeningDebugger.scala
scala-debugger-test/src/main/scala/org/senkbeil/test/misc/LaunchingMain.scala
scala-debugger-test/src/main/scala/org/senkbeil/test/misc/ListeningMain.scala

1. Added launching and listening debugger integration tests
2. Updated test helpers to include jvm classpath method
3. Updated launching debugger to use jvm classpath method
4. Added method on listening debugger to indicate if multiple connections are supported

Added launching/listening debugger integration tests

---

build.sbt
project/build.properties

Fix integration tests always succeeding

---

scala-debugger-api/src/it/resources/log4j.properties
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/methods/MethodEntryManagerIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/CustomPropertyFilter.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/MethodNameFilter.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/CustomPropertyFilterProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/MaxTriggerFilterProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/MethodNameFilterProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/MinTriggerFilterProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/methods/MethodEntryManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/virtualmachines/ScalaVirtualMachine.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/filters/MethodNameFilterSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/MethodNameFilterProcessorSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/methods/MethodEntryManagerSpec.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/methods/MethodEntry.scala

Add method entry manager

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/methods/MethodExitManagerIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/methods/MethodExitManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/virtualmachines/ScalaVirtualMachine.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/methods/MethodExitManagerSpec.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/methods/MethodExit.scala

Added method exit manager

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/exceptions/ExceptionManagerIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/exceptions/ExceptionManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/virtualmachines/ScalaVirtualMachine.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/exceptions/ExceptionManagerSpec.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/exceptions/CustomException.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/exceptions/InsideFunctionalTryException.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/exceptions/InsideTryBlockException.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/exceptions/OutsideTryException.scala

Added exception manager

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/jdi/events/data/CustomPropertyDataRequestIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/jdi/events/filters/CustomPropertyFilterIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/breakpoints/BreakpointManager.scala

Refactored breakpoint manager to accept enabled/suspend policy as jdi arguments with defaults

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/steps/StepManagerIntegrationSpec.scala

Updated max test duration for skipping iterations to 10 seconds

---

scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/AndFilter.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/NotFilter.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/OrFilter.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/AndFilterProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/NotFilterProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/OrFilterProcessor.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/filters/AndFilterSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/filters/NotFilterSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/filters/OrFilterSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/AndFilterProcessorSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/NotFilterProcessorSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/filters/processors/OrFilterProcessorSpec.scala

Added and, or, and not filters

---

scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/JDIEventArgumentProcessor.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/data/JDIEventDataError.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/jdi/events/data/JDIEventDataUnknownError.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/jdi/events/JDIEventArgumentProcessorSpec.scala

Added data error class and transforming of errors from data requests

---

scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/FilterNotOperation.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/FilterOperation.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/FlatMapOperation.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/ForeachOperation.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/MapOperation.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/NoOperation.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/Operation.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/Pipeline.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/FilterNotOperationSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/FilterOperationSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/FlatMapOperationSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/ForeachOperationSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/MapOperationSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/NoOperationSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/PipelineSpec.scala

Added pipeline and operations

---

scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/events/EventManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/CloseOperation.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/CloseablePipeline.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/Pipeline.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/events/EventManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/CloseOperationSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/CloseablePipelineSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/PipelineSpec.scala

Added stream creation methods to event manager, added closeable functionality to pipeline

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/breakpoints/PureBreakpointProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMDisconnectProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMStartProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/test/VirtualMachineFixtures.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/SwappableDebugProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/PureDebugProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMDisconnectProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMStartProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/traits/DebugProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/traits/vm/VMDisconnectProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/traits/vm/VMStartProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/virtualmachines/ScalaVirtualMachine.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/SwappableDebugProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMDisconnectProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMStartProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/traits/vm/VMDisconnectProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/traits/vm/VMStartProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/virtualmachines/ScalaVirtualMachineSpec.scala
scala-debugger-api/src/test/scala/test/JDIMockHelpers.scala

Added VMStart and VMDisconnect pure profiles

---

scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/Pipeline.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/PipelineSpec.scala

Added failed pipeline path

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/events/PureEventProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/events/PureEventProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/events/PureEventProfileSpec.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/events/LoopingEvent.scala

Added pure event profile logic

---

scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/breakpoints/BreakpointManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/exceptions/ExceptionManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/methods/MethodEntryManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/methods/MethodExitManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/breakpoints/PureBreakpointProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/breakpoints/BreakpointManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/exceptions/ExceptionManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/methods/MethodEntryManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/methods/MethodExitManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/breakpoints/PureBreakpointProfileSpec.scala

Updated low-level APIs to use try

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/exceptions/PureExceptionProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/breakpoints/PureBreakpointProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/exceptions/PureExceptionProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/exceptions/PureExceptionProfileSpec.scala

Added pure exception profile implementation

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/methods/PureMethodEntryProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/methods/PureMethodEntryProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/methods/PureMethodEntryProfileSpec.scala
scala-debugger-api/src/test/scala/test/JDIMockHelpers.scala

Added pure method entry profile implementation

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/methods/PureMethodExitProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/methods/PureMethodExitProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/methods/PureMethodExitProfileSpec.scala
scala-debugger-api/src/test/scala/test/JDIMockHelpers.scala

Added pure method exit profile implementation

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/lowlevel/vm/VMDeathManagerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMDeathProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/ManagerContainer.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/vm/VMDeathManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/PureDebugProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMDeathProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/vm/VMDeathManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMDeathProfileSpec.scala

Added VMDeath low-level api, added VMDeath pure profile

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/lowlevel/threads/ThreadDeathManagerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/lowlevel/vm/VMDeathManagerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/threads/PureThreadDeathProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMDeathProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/ManagerContainer.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/threads/ThreadDeathManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/PureDebugProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/threads/PureThreadDeathProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/virtualmachines/ScalaVirtualMachine.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/threads/ThreadDeathManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/threads/PureThreadDeathProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMDeathProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/vm/PureVMStartProfileSpec.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/threads/ThreadDeath.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/threads/ThreadStart.scala

Added ThreadDeath low-level api, added ThreadDeath pure profile

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/lowlevel/threads/ThreadStartManagerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/threads/PureThreadStartProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/ManagerContainer.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/threads/ThreadStartManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/PureDebugProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/threads/PureThreadStartProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/virtualmachines/ScalaVirtualMachine.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/threads/ThreadStartManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/threads/PureThreadStartProfileSpec.scala

Added ThreadStart low-level api, added ThreadStart pure profile

---

build.sbt
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/breakpoints/BreakpointManager.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/breakpoints/BreakpointManagerSpec.scala

Updated low-level breakpoint removal to also remove pending breakpoints

---

scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/breakpoints/BreakpointManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/breakpoints/ExtendedBreakpointManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/classes/ClassPrepareManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/classes/ClassUnloadManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/events/EventManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/exceptions/ExceptionManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/methods/MethodEntryManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/methods/MethodExitManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/monitors/MonitorContendedEnterManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/monitors/MonitorContendedEnteredManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/monitors/MonitorWaitManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/monitors/MonitorWaitedManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/threads/ThreadDeathManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/threads/ThreadStartManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/vm/VMDeathManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/utils/MultiMap.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/breakpoints/BreakpointManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/exceptions/ExceptionManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/methods/MethodEntryManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/methods/MethodExitManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/utils/MultiMapSpec.scala

Fix duplicate input for managers

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/lowlevel/steps/StepManagerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/steps/PureStepProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/steps/StepManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/pipelines/Pipeline.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/steps/PureStepProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/swappable/steps/SwappableStepProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/traits/steps/StepProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/steps/StepManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/pipelines/PipelineSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/steps/PureStepProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/swappable/steps/SwappableStepProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/traits/steps/StepProfileSpec.scala

Refactor step manager

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/lowlevel/watchpoints/AccessWatchpointManagerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/watchpoints/PureAccessWatchpointProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/ManagerContainer.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/breakpoints/BreakpointManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/watchpoints/AccessWatchpointManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/watchpoints/NoFieldFound.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/PureDebugProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/watchpoints/PureAccessWatchpointProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/watchpoints/PureModificationWatchpointProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/swappable/watchpoints/SwappableAccessWatchpointProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/swappable/watchpoints/SwappableModificationWatchpointProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/traits/watchpoints/AccessWatchpointProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/traits/watchpoints/ModificationWatchpointProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/watchpoints/AccessWatchpointManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/watchpoints/PureAccessWatchpointProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/swappable/watchpoints/SwappableAccessWatchpointProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/swappable/watchpoints/SwappableModificationWatchpointProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/traits/watchpoints/AccessWatchpointProfileSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/traits/watchpoints/ModificationWatchpointProfileSpec.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/watchpoints/AccessWatchpoint.scala
scala-debugger-test/src/main/scala/org/senkbeil/debugger/test/watchpoints/ModificationWatchpoint.scala

Add access watchpoint support

---

scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/lowlevel/watchpoints/ModificationWatchpointManagerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/senkbeil/debugger/api/profiles/pure/watchpoints/PureModificationWatchpointProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/ManagerContainer.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/watchpoints/AccessWatchpointManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/lowlevel/watchpoints/ModificationWatchpointManager.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/PureDebugProfile.scala
scala-debugger-api/src/main/scala/org/senkbeil/debugger/api/profiles/pure/watchpoints/PureModificationWatchpointProfile.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/lowlevel/watchpoints/ModificationWatchpointManagerSpec.scala
scala-debugger-api/src/test/scala/org/senkbeil/debugger/api/profiles/pure/watchpoints/PureModificationWatchpointProfileSpec.scala

Add modification watchpoint support

---

CONTRIBUTING.md
README.md
docs/about/contributing.md
docs/about/roadmap.md
docs/index.md
mkdocs.yml
project/Common.scala

Updated references to chipsenkbeil/scala-debugger and chipsenkbeil/scala-debugger-api to ensime/scala-debugger

---

.drone.yml
project/Common.scala
project/build.properties

1. Updated Scala versions to 2.10.6 and 2.11.8 (updated Common as well)
2. Updated sbt version in build.properties to 0.13.11
3. Updated drone file test run to do both unit and integration together

Updated drone file

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureArrayInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureLocalVariableInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureValueInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ThreadInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureArrayInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureValueInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Refactored info classes to have thread info inherit object info, added unique id to object info

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureLocalVariableInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureLocalVariableInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/VariableInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Adds a companion setValue method to variables

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureReferenceTypeInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureClassLoaderInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureClassObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureLocationInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureReferenceTypeInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ClassLoaderInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ClassObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/LocationInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ReferenceTypeInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureClassLoaderInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureClassObjectInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureLocationInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureReferenceTypeInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/LocationInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala
scala-debugger-test/src/main/scala/org/scaladebugger/test/info/Classes.scala

Added location, reference type, class object, and class loader info profiles

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureMiscInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureMiscInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/swappable/info/SwappableMiscInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/MiscInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureMiscInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/swappable/info/SwappableMiscInfoProfileSpec.scala
scala-debugger-test/src/main/scala/org/scaladebugger/test/info/MultiSource.scala
scala-debugger-test/src/main/scala/org/scaladebugger/test/info/package1/ScalaSource.scala
scala-debugger-test/src/main/scala/org/scaladebugger/test/info/package2/ScalaSource.scala

Added sourceNameToPaths method to misc profile

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/FrameInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Resolves #176 and #175 (indirectly through location).

Added location retrieval to stack frame profile

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ThreadInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ObjectInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ThreadInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala
scala-debugger-test/src/main/scala/org/scaladebugger/test/info/Frames.scala

Added frames(index, length) method to thread profile

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureMiscInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureMiscInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/swappable/info/SwappableMiscInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/MiscInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureMiscInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/swappable/info/SwappableMiscInfoProfileSpec.scala

Added high-level ability to create (mirror) values remotely from local values

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureTypeInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureValueInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/CastNotPossibleException.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/PrimitiveTypeInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/TypeInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/TypeInfoProfileSpec.scala
scala-debugger-test/src/main/scala/org/scaladebugger/test/info/Variables.scala

Added type casting to type info

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureLocalVariableInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureLocalVariableInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureReferenceTypeInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/IndexedVariableInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ReferenceTypeInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ThreadInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/VariableInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/FrameInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureReferenceTypeInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ObjectInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ReferenceTypeInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ThreadInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/VariableInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Add index information to field variables

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Added method to wrap object in profile

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Added class retrieval, added optional class/thread retrieval, added full thread retrieval

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Resolves #229 without the DSL.

Add other wrapper methods

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureClassTypeInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureClassTypeInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureReferenceTypeInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ClassTypeInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ReferenceTypeInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/FrameInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureClassTypeInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureReferenceTypeInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/FrameInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ObjectInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ReferenceTypeInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Added optional methods for info profiles where null could be returned

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureArrayInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureArrayTypeInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureFrameInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureMiscInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureValueInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/dsl/info/VariableInfoDSLWrapper.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureLocalVariableInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureObjectInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureStringInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureValueInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/StringInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ValueInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/VariableInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/VariableInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureFieldInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureLocalVariableInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureStringInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureValueInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/StringInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ValueInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/VariableInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Add string info profile

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfile.scala

Add vm methods

---

scala-debugger-api/src/it/scala/test/VirtualMachineFixtures.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/lowlevel/ManagerContainer.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/virtualmachines/DummyScalaVirtualMachine.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/virtualmachines/ScalaVirtualMachine.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/virtualmachines/StandardScalaVirtualMachine.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/ObjectInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/ValueInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/VariableInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/virtualmachines/DummyScalaVirtualMachineSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/virtualmachines/ScalaVirtualMachineSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/virtualmachines/StandardScalaVirtualMachineSpec.scala

Fixed issue of pending requests, added suspend/resume to vm

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureThreadStatusInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ThreadInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ThreadStatusInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureThreadStatusInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ThreadStatusInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Added thread status profile and resume/suspend methods for thread profile

---

appveyor.yml
project/Common.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/lowlevel/vm/StandardVMDeathManagerIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureMiscInfoProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/vm/PureVMDeathProfileIntegrationSpec.scala
scala-debugger-api/src/it/scala/test/Constants.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/utils/JDIToolsSpec.scala

Add windows testing

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureThreadGroupInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ThreadGroupInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ThreadInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureThreadGroupInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/swappable/info/SwappableGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ThreadGroupInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Added ThreadGroupInfo profile and retrieval methods

---

scala-debugger-api/src/it/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileIntegrationSpec.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureGrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/GrabInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala
scala-debugger-test/src/main/scala/org/scaladebugger/test/info/Threads.scala

Add thread lookup by name

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureInfoProducerProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureReferenceTypeInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureThreadGroupInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureThreadInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/pure/info/PureValueInfoProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/InfoProducerProfile.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/ValueInfoProfile.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/pure/info/PureValueInfoProfileSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/traits/info/ValueInfoProfileSpec.scala
scala-debugger-api/src/test/scala/test/InfoTestClasses.scala

Added missing conversion methods

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/debuggers/AttachingDebugger.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/debuggers/Debugger.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/debuggers/LaunchingDebugger.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/debuggers/ListeningDebugger.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/debuggers/ProcessDebugger.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/virtualmachines/DummyScalaVirtualMachine.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/virtualmachines/ScalaVirtualMachine.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/virtualmachines/StandardScalaVirtualMachine.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/debuggers/AttachingDebuggerSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/debuggers/DebuggerSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/debuggers/LaunchingDebuggerSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/debuggers/ListeningDebuggerSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/debuggers/ProcessDebuggerSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/ObjectInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/ValueInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/dsl/info/VariableInfoDSLWrapperSpec.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/virtualmachines/ScalaVirtualMachineSpec.scala

Added ability to specify default profile on startup/connection of vms

---

.drone.yml
Dockerfile
appveyor.yml
build.sbt
project/Common.scala
project/Macros.scala
project/SbtPlugin.scala
project/plugins.sbt

Added sbt-doge to combat different cross version compilation

---

docs/src/about/contributing.md
docs/src/about/license.md
docs/src/about/release-notes.md
docs/src/about/roadmap.md
docs/src/about/us.md
scala-debugger-docs/src/main/scala/org/scaladebugger/docs/layouts/FrontPage.scala

Resolves #296. Will add compatibility section later.

Updated about section, added us page

---

scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/java/info/events/JavaModificationWatchpointEventInfo.scala
scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/traits/info/events/ModificationWatchpointEventInfo.scala
scala-debugger-api/src/test/scala/org/scaladebugger/api/profiles/java/info/events/JavaModificationWatchpointEventInfoSpec.scala

Added missing valueToBe method on modification watchpoint event wrapper
